# Generated by Django 2.1.8 on 2019-05-04 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='writer_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
